CREATE OR REPLACE TRIGGER restricted_insert
BEFORE INSERT ON emp_table
DECLARE 
CHECK_HOURS_ERROR EXCEPTION;
PRAGMA EXCEPTION_INIT(CHECK_HOURS_ERROR,-20001);
BEGIN
IF (TO_CHAR(SYSDATE,'HH24:MI') NOT BETWEEN '09:00' AND '18:00') THEN
    RAISE CHECK_HOURS_ERROR;
END IF;
EXCEPTION
WHEN CHECK_HOURS_ERROR THEN
     dbms_output.put_line('You can add employee only between 9:00 AM and 6:00 PM');
END;
/         