CREATE OR REPLACE TRIGGER customer_sal
BEFORE INSERT OR UPDATE ON customers
FOR EACH ROW
DECLARE 
LESS_SALARY EXCEPTION;
PRAGMA EXCEPTION_INIT(LESS_SALARY,-20002);
BEGIN
IF :NEW.SALARY < :OLD.SALARY THEN
        RAISE_APPLICATION_ERROR(-20002,'NEW SALARY CAN NOT BE LESS THAN OLD ONE')  ;
END IF;

EXCEPTION
WHEN LESS_SALARY THEN 
DBMS_OUTPUT.PUT_LINE(sqlerrm);
END;
/        