DECLARE
    CURSOR CUR_EMPLOYEE IS
        SELECT
            EMP_FNAME
        FROM
            EMPLOYEE;
    V_EMP_FNAME EMPLOYEE.EMP_FNAME%TYPE;
BEGIN
    OPEN CUR_EMPLOYEE;
    LOOP
        FETCH CUR_EMPLOYEE INTO V_EMP_FNAME;
        IF CUR_EMPLOYEE%NOTFOUND THEN
            EXIT;
        END IF;
        DBMS_OUTPUT.PUT_LINE('employee firstName is :'
            ||V_EMP_FNAME);
    END LOOP;
    CLOSE CUR_EMPLOYEE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SOME ERROR OCCURS');
END;
/