DECLARE

NUM_V number:=&NUM_V;
MYSELECTOR NUMBER;

BEGIN 

MYSELECTOR:=MOD(NUM_V,2);

CASE MYSELECTOR

WHEN 0 THEN 
DBMS_OUTPUT.PUT_LINE(NUM_V||' IS AN EVEN NUMBER');
ELSE
DBMS_OUTPUT.PUT_LINE(NUM_V||' IS AN ODD NUMBER');
END CASE;
DBMS_OUTPUT.PUT_LINE(' DONE ');
EXCEPTION

WHEN OTHERS THEN 
DBMS_OUTPUT.PUT_LINE(' SOME ERRORS OCCUR ');

END;
/